### ISSUE TITLE
why the result is bad?

### ISSUE THREAD

**Issue by YiChenCityU** [zhuhao-nju/rafare#4]
![jcc_vis](https://user-images.githubusercontent.com/12424523/225916668-ca0fba2e-bb14-4dc1-b809-60879d78e2c7.png)

**Comment by longwg** [comment]
![img_pad_vis](https://github.com/zhuhao-nju/rafare/assets/47819762/cd9bb6c7-7340-44e7-b81a-0a3f9c195e77)

Because the position of the face in the image is not very suitable, this is the result of scaling the original image by 0.6.

**Comment by longwg** [comment]
Later we will add preprocessing code in the input part to avoid the problem of face scale.
